CREATE TABLE EMPRESTIMOS (
  COD_EMPRESTIMOS INT UNIQUE NOT NULL,
  TITULO VARCHAR(20),
  NUMERO_DA_CARTEIRINHA INT UNIQUE NOT NULL,
  CPF INT UNIQUE NOT NULL,
  PRIMARY KEY(COD_EMPRESTIMOS)
  FOREIGN KEY(CPF) REFERENCES USUARIO(CPF)
  FOREIGN KEY(COD_EMPRESTIMOS) REFERENCES LIVROS(COD_EMPRESTIMOS)
  );