CREATE TABLE LIVROS (
  COD_LIVROS INT UNIQUE NOT NULL,
  COD_EDITORA INT,
  COD_AUTOR INT,
  COD_GENERO INT,
  COD_EMPRESTIMOS INT,
  TITULO VARCHAR(20),
  EDIÇAO VARCHAR(10),
  VOLUME INT NOT NULL,
  PRIMARY KEY(COD_LIVROS)
  FOREIGN KEY (COD_EMPRESTIMOS) REFERENCES EMPRESTIMOS(COD_EMPRESTIMOS)
  FOREIGN KEY (COD_EDITORA) REFERENCES EDITORA(cod_editora)
  FOREIGN KEY (COD_GENERO) REFERENCES GENERO(cod_genero)
 
  
  );